### ISSUE TITLE
Add blog capability and copy over all nmfs-openscapes tagged posts

### ISSUE THREAD

**Issue by jules32** [nmfs-openscapes/nmfs-openscapes.github.io#20]
Hi @stefaniebutland, could you please add blog capability and copy over all nmfs-openscapes tagged posts, as you did with Pathways?

Let's first see whether you can add the blog to the existing website setup (which currently looks like a book with the left navbar rather than a website with top navbar). I suspect that we will soon re-present this website with the top navbar, but hopefully that decision won't get in your way to set up the blog posts. 

Thank you!

**Comment by stefaniebutland** [comment]
@jules32 requesting your Git help please. Screenshare might be best to resolve it.

I [merged PR](https://github.com/nmfs-openscapes/nmfs-openscapes.github.io/pulls?q=is%3Apr+is%3Amerged) to create Blog and add all posts. [Build failed](https://github.com/nmfs-openscapes/nmfs-openscapes.github.io/actions/runs/10293129509/job/28488844551#step:4:100) (error below). 
> [15/40] blog/2023-05-17-mentor-coach/index.qmd
> Error in loadNamespace(x) : there is no package called ‘rmarkdown’

Realized I should change Rmarkdown formatted images into Quarto style for 1 or more posts, so I reverted that PR. I still have my local & remote branch `add-blog` but not sure what Git/ GitHub approach to take to add my changes.

🤔 Tempted to revert my reversion, then start new PR for fixes but not sure  🤔

**Comment by jules32** [comment]
Hi @stefaniebutland yes I think you're right to reformat images with Quarto style, thanks for doing that. I would probably revert and start a new PR too. Do you want to try that, and then we can screenshare Monday if needed?

**Comment by stefaniebutland** [comment]
So good that we're coworking Monday!

**Comment by stefaniebutland** [comment]
Jumping up and down! It worked! 
Closing as completed

**Comment by jules32** [comment]
Woo! Great job @stefaniebutland , and awesome that it shows up no problem in the left navbar working how we'd expect. Let's not think about reworking with top navbar for now :)

Thank you!
