### ISSUE TITLE
add Mentor kickoff plan

### ISSUE THREAD

**Issue by jules32** [nmfs-openscapes/nmfs-openscapes.github.io#3]
- kickoff date - Oct 17
  - structure of mentors meeting in the begining
- how many staff involved for mentors
- Q3 plan
- links

**Comment by jules32** [comment]
play-by-play nasa mentors: https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/blob/4f9b39e3453b7128913cfb4932f79eb5f602176c/mentors.qmd#L55

8h/month

@eeholmes

**Comment by stefaniebutland** [comment]
done
