### ISSUE TITLE
Add 2024 Champions page

### ISSUE THREAD

**Issue by jules32** [nmfs-openscapes/nmfs-openscapes.github.io#62]
Hi @stefaniebutland , 

Could you please add the 2024 Champions cohort in 2 places? It will be a bit of a "stub" for now and we'll add more after the Pathways presentations next week. 

- [x] Update upcoming vs past
- [x] Add a new page, with as much as you can to look something like https://nmfs-openscapes.github.io/cohorts/SEFSC-sum2022.html
- [x] Review https://nmfs-openscapes.github.io/champions.html; maybe write in italics at the top *this is the page in preparation for the 2024 cohort; check back as we prepare for fall 2025!*

If you're able to start the 2024 pages this week, we can update during our Dec 5 coworking!

**Comment by stefaniebutland** [comment]
draft PR https://github.com/nmfs-openscapes/nmfs-openscapes.github.io/pull/63

**Comment by stefaniebutland** [comment]
note to self: add cohort b zoomie

**Comment by jules32** [comment]
@stefaniebutland done! Thank you!

**Comment by stefaniebutland** [comment]
closed as completed
